### ISSUE TITLE
examples install instructions not working

### ISSUE THREAD

**Issue by trapperkeeper** [SoftInstigate/restheart-customization-examples#1]
Step 3, 'mvn package', is not working. Build fails with the following error:

[ERROR] Failed to execute goal on project restheart-customization-examples: Could not resolve dependencies for project com.softinstigate:restheart-customization-examples:jar:1.0-SNAPSHOT: Could not find artifact org.restheart:restheart:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)

**Comment by mkjsix** [comment]
Hi @trapperkeeper 
This repo hasn't been update in 3 years, so it was completely out of synch. I tried to update to the latest 3.x SNAPSHOT but I had not time to test it, at least it compiles now... Please give it a try.

**Comment by trapperkeeper** [comment]
I changed the restheart dependency, in the pom file, from 3.3.0-SNAPSHOT to 3.2.2, since that is the latest in the public repos, and it builds for me. I'll update further when I have a chance to play with it. Thanks.

**Comment by mkjsix** [comment]
Good point, I did the same setting to 3.2.2
